# ==============================
# CPI分析条件
# ==============================

# CPI状況
CPI_INFLATION_THRESHOLD = 2.0
CPI_DISINFLATION_THRESHOLD = 0.55

# CPIトレンド
CPI_TREND_INCREASE_THRESHOLD = 0.2
CPI_TREND_DECREASE_THRESHOLD = -0.2


# ==============================
# 雇用分析条件
# ==============================

# 雇用者数
EMPLOYMENT_YOY_THRESHOLD = 0.0

UNEMPLOYMENT_YOY_THRESHOLD = 0.0

# 失業率
UNEMPLOYMENT_IMPROVEMENT_THRESHOLD = 0.0
UNEMPLOYMENT_DECLINE_THRESHOLD = 0.0

# 平均時給
WAGE_IMPROVEMENT_THRESHOLD = 3.0
WAGE_DECLINE_THRESHOLD = 0.0

# 雇用総合判断
EMPLOYMENT_IMPROVEMENT_SCORE_THRESHOLD = 2
EMPLOYMENT_DECLINE_SCORE_THRESHOLD = -2

# 雇用トレンド
EMPLOYMENT_TREND_INCREASE_THRESHOLD = 0.2
EMPLOYMENT_TREND_DECREASE_THRESHOLD = -0.2

# 失業率トレンド
UNEMPLOYMENT_TREND_IMPROVEMENT_THRESHOLD = -0.2
UNEMPLOYMENT_TREND_DECLINE_THRESHOLD = 0.2

# 平均時給トレンド
WAGE_TREND_INCREASE_THRESHOLD = 0.2
WAGE_TREND_DECREASE_THRESHOLD = -0.2


# ==============================
# 金利分析条件
# ==============================

# 金利水準
RATE_HIGH_THRESHOLD = 3.75
RATE_NEUTRAL_THRESHOLD = 2.0

# 金利トレンド
RATE_HIKE_THRESHOLD = 0.25
RATE_CUT_THRESHOLD = -0.25